#!/bin/bash
# Set elasticsearch cluster name
# Disable dynamic scripting as per http://www.elasticsearch.org/blog/scripting-security
cat >> /opt/elasticsearch/config/elasticsearch.yml << EOF
cluster.name: $ES_CLUSTER_NAME
script.disable_dynamic: true
EOF

/usr/bin/supervisord -c /etc/supervisor/conf.d/elasticsearch.conf
